global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'micro-sender'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['micro-sender:8081']

  - job_name: 'micro-recipient'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['micro-recipient:8082']

  - job_name: 'micro-collector'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['micro-collector:8083']
      
   - job_name: 'micro-visualizer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['micro-visualizer:8084']