server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: app
    password: app
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: micro-sender