server:
  port: 8083
recipient:
  base-url: http://localhost:8082
collector:
  fetch-interval-ms: 10000
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: micro-collector

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: postgresql://localhost:5432/appdb
    username: app
    password: app